### ISSUE TITLE
Could not find module 'discid.dll'

### ISSUE THREAD

**Issue by omgitsraven** [JonnyJD/musicbrainz-isrcsubmit#124]
I'm running `isrcsubmit.bat` from isrcsubmit 2.1.0, and it just immediately says this:

```
Traceback (most recent call last):
  File "C:\OtherPrograms\isrcsubmit-2.1.0-win32\isrcsubmit.py", line 47, in <module>
    import discid
  File "C:\OtherPrograms\isrcsubmit-2.1.0-win32\discid\__init__.py", line 30, in <module>
    from discid.disc import read, put, Disc, DiscError, TOCError
  File "C:\OtherPrograms\isrcsubmit-2.1.0-win32\discid\disc.py", line 24, in <module>
    from discid.libdiscid import _LIB, FEATURES
  File "C:\OtherPrograms\isrcsubmit-2.1.0-win32\discid\libdiscid.py", line 108, in <module>
    _LIB = _open_library(_LIB_NAME)
  File "C:\OtherPrograms\isrcsubmit-2.1.0-win32\discid\libdiscid.py", line 99, in _open_library
    return ctypes.cdll.LoadLibrary(lib_name)
  File "C:\Users\Hazel\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Hazel\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'discid.dll'. Try using the full path with constructor syntax.

Press any key to continue . . .
```

There's definitely a `discid.dll` in the same folder as isrcsubmit.bat, so I'm not sure how it isn't finding it...

**Comment by omgitsraven** [comment]
Aha, looks like it's this: https://stackoverflow.com/questions/59014318/filenotfounderror-could-not-find-module-libvlc-dll
(Plus, after that, I also had to follow these instructions: https://github.com/JonnyJD/musicbrainz-isrcsubmit/issues/73 )

**Comment by omgitsraven** [comment]
This pull request fixes it for me: https://github.com/JonnyJD/musicbrainz-isrcsubmit/pull/125
